; ================================================================================
; PlatformIO Project Configuration: Modular Sensor Endpoint (ESP32-C3 BLE 5.0)
; Enterprise Smart Building Wireless Smoke & Security Ecosystem
; ================================================================================

[platformio]
default_envs = esp32c3_endpoint
description = Battery-Powered Smoke & Security Sensor Endpoint (ESP32-C3 BLE 5.0 Beacon / Deep-Sleep)

[env:esp32c3_endpoint]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
build_flags =
    -D CORE_DEBUG_LEVEL=3
